Also print a memory usage table
MilesCranmer/AirspeedVelocity.jl pull request #32
Opened 2024-02-22 10:52 UTC by abelsiqueira

By default, a second table with the number of allocations and memory usage will be printed as well. This can be suppressed with the flag --hide-memory.

Example output:

```
$ ~/.julia/bin/benchpkgtable AirspeedVelocity --rev v0.4.4,v0.4.3
[ Info: Loading results from ./results_AirspeedVelocity@v0.4.4.json
[ Info: Flattening results.
[ Info: Loading results from ./results_AirspeedVelocity@v0.4.3.json
[ Info: Flattening results.
|                   | v0.4.4          | v0.4.3          |
|:------------------|:---------------:|:---------------:|
| main/random_sleep | 0.532 ± 0.44 s  | 0.404 ± 0.28 s  |
| time_to_load      | 0.338 ± 0.002 s | 0.34 ± 0.0053 s |

|                   | v0.4.4                  | v0.4.3                  |
|:------------------|:-----------------------:|:-----------------------:|
| main/random_sleep | 4  allocs: 0.112 kB     | 4  allocs: 0.112 kB     |
| time_to_load      | 0.214 M allocs: 14.5 MB | 0.217 M allocs: 14.6 MB |
```

2024-02-22 11:38 UTC, MilesCranmer requested changes
Nice!! Looks good. I was wondering if you could change the CLI flags to be as follows instead?

```bash
benchpkgtable --mode=memory
```

where the default `--mode=time`. And `--mode=time,memory` would be like what you have now.

Since you can't output two tables at once this will make it easier to partition the `benchmark_pr.yml` command so the memory table can be collapsed by default.

2024-02-22 11:41 UTC, MilesCranmer commented
Also I'm not sure why but the columns seem to be `median` and `memory` in the ratio column?

<img width="508" alt="Screenshot 2024-02-22 at 11 41 36" src="https://github.com/MilesCranmer/AirspeedVelocity.jl/assets/7593028/90e5bb24-7296-43ca-a73f-d5e962e5384a">

2024-02-23 12:24 UTC, MilesCranmer commented on test/test_benchmark.jl
> +    |        | v1           | v2         | median v1/v2 |
Maybe should be "time v1/v2"?

2024-02-23 12:25 UTC, MilesCranmer commented on test/test_benchmark.jl
> +    |        | v1           | v2         | median v1/v2 |
Or just v1/v2 honestly!

2024-02-26 17:57 UTC, MilesCranmer commented on src/Utils.jl
> +    units = [(1.0, "B"), (1e-3, "kB"), (1e-6, "MB"), (1e-9, "GB")]
I think kB should be `1/1024` rather than `1/1000`, right?

2024-02-26 18:01 UTC, MilesCranmer commented on src/Utils.jl
> +    units = [(1.0, "B"), (1e-3, "kB"), (1e-6, "MB"), (1e-9, "GB")]
I fixed this but the test needs to be updated too which seems trickier.

2024-02-26 19:24 UTC, MilesCranmer approved these changes

2024-02-26 19:29 UTC, merged

2024-02-26 19:29 UTC, MilesCranmer commented
Thanks @abelsiqueira!!

2024-02-26 22:06 UTC, abelsiqueira commented
Thanks for the updates and the merge, @MilesCranmer.